### PR TITLE
Cart Workflow - ICDC Bentofication

### PR DESCRIPTION
**Pull request by iksheth**
1)~~Imported ICDC's theme styling. It is overridden in light.js theme only. **IMPACTING GLOBALLY**~~ 
( covered in https://github.com/CBIIT/bento-icdc-frontend/pull/27 ) 
2) Added external icon property for cart custodian
3) Modified Style and GraphQL queries to get files from list
4) updated cart controller to support ICDC's uuid instead of Bento's fileId property
5) Updated cartIcon in Navbar

### CODE REVIEW

**Review by jonkiky — APPROVED** [review]
LGTM!

**Comment by skiran86** [comment]
@iksheth Conflicts

**Comment by iksheth** [comment]
> @iksheth Conflicts

Looking into it.

**Comment by AjayDoddapaneni** [comment]
Looks like multiple changes happened here?

**Pull request closed without merging**
