### PR TITLE
icdc_2279 update query to include all the files associated to case

### PR DESCRIPTION
**Pull request by rana22**
### Bug Fixes
update query to include all the files associated to cases

### CODE REVIEW

**Review by AustinSMueller — CHANGES_REQUESTED** [review]
I think the change is okay but changes to caseOverviewPaged should be implemented in caseOverviewPagedDesc as well

**Review by n2iw — CHANGES_REQUESTED** [review]
Same as Austin's comment, caseOverviewPagedDesc need to be changed also.

**Comment by rana22** [comment]
> I think the change is okay but changes to caseOverviewPaged should be implemented in caseOverviewPagedDesc as well

I have updated the query according to feedback.

**Review by n2iw — APPROVED** [review]
It looks good to me now.

**Pull request merged**
