### PR TITLE
icdc_1948 - sample profile visualization query update

### PR DESCRIPTION
**Pull request by rana22**

### CODE REVIEW

**Comment by tyudosen** [comment]
Looks good, but if you have time the change all queries to fit this example

`
  studySampleSiteCount(study_code: String): [GroupCount] @cypher(statement: """
    MATCH (s:study)
      WHERE s.clinical_study_designation = $study_code
    OPTIONAL MATCH (c:case) --> (s)
    OPTIONAL MATCH (c) <-- (samp: sample)
    WITH DISTINCT(samp.sample_site) AS group, COUNT(samp) AS counts where counts > 0
    RETURN {
      group: group,
      count: counts
   }
  """, passThrough: true)
`

to 

`
studySampleSiteCount(study_codes: [String]): [GroupCount] @cypher(statement: """
    MATCH (s:study)
      WHERE s.clinical_study_designation IN $study_codes
    OPTIONAL MATCH (c:case) --> (s)
    OPTIONAL MATCH (c) <-- (samp: sample)
    WITH DISTINCT(samp.sample_site) AS group, COUNT(DISTINCT samp) AS counts 
    WHERE counts > 0
    RETURN {
      group: group,
      count: counts
   }
  """, passThrough: true)
`


- Making the study_codes parameter an array would just increase flexibility in case there is a need for multiple inputs in the future
- "COUNT(DISTINCT samp)" the distinct shouldn't be necessary as there should only be one sample per case but this would prevent counting duplicates in case that edge case happens for some reason
- Moving "WHERE counts > 0" to its own line is just to standardize the format to match the other queries

**Comment by rana22** [comment]
> Looks good, but if you have time the change all queries to fit this example
> 
> `studySampleSiteCount(study_code: String): [GroupCount] @cypher(statement: """ MATCH (s:study) WHERE s.clinical_study_designation = $study_code OPTIONAL MATCH (c:case) --> (s) OPTIONAL MATCH (c) <-- (samp: sample) WITH DISTINCT(samp.sample_site) AS group, COUNT(samp) AS counts where counts > 0 RETURN { group: group, count: counts } """, passThrough: true)`
> 
> to
> 
> `studySampleSiteCount(study_codes: [String]): [GroupCount] @cypher(statement: """ MATCH (s:study) WHERE s.clinical_study_designation IN $study_codes OPTIONAL MATCH (c:case) --> (s) OPTIONAL MATCH (c) <-- (samp: sample) WITH DISTINCT(samp.sample_site) AS group, COUNT(DISTINCT samp) AS counts WHERE counts > 0 RETURN { group: group, count: counts } """, passThrough: true)`
> 
> * Making the study_codes parameter an array would just increase flexibility in case there is a need for multiple inputs in the future
> * "COUNT(DISTINCT samp)" the distinct shouldn't be necessary as there should only be one sample per case but this would prevent counting duplicates in case that edge case happens for some reason
> * Moving "WHERE counts > 0" to its own line is just to standardize the format to match the other queries

updated

**Comment by tyudosen** [comment]
Change

`COUNT(samp)`

to

`COUNT(DISTINCT samp)`

**Comment by rana22** [comment]
updated

**Review by tyudosen — APPROVED** [review]
LGTM

**Pull request merged**
