### PR TITLE
NO-ISSUE-CSV-FIX

### PR DESCRIPTION
**Pull request by ty-esi**
### Bug Fixes
- Fixes csv download bug.

### CODE REVIEW

**Review by rana22 — APPROVED** [review]
LGTM

**Review by iksheth — COMMENTED** [review]
Looks good to me. 

@tyudosen Is this PR added to Bug ticket comments?

**Comment by iksheth** [comment]
@rana22 @tyudosen Please delete branches after merge using "Delete Branch" button in PR UI.

**Comment by ty-esi** [comment]
@iksheth Yes, I have it added in the comments here https://tracker.nci.nih.gov/browse/ICDC-3472

**Comment by iksheth** [comment]
Perfect Thanks @ty-esi

**Pull request merged**
